# Generated by Django 4.0.6 on 2022-07-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='photo',
            field=models.ImageField(upload_to='%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
