# Generated by Django 4.0.6 on 2022-07-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_slug_new_slug_alter_new_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'Ошибка в URL'}, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
